[project]
name = "pixel"
version = "0.1.0"
description = "A Python project for converting uploaded photos into pixel art with AI."
readme = "README.md"
authors = [
    { name = "ddddelicious", email = "2561882819@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.3.0",
]

[project.scripts]
pixel = "pixel:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
